import type { Metadata } from "next"
import { Geist, Geist_Mono, Inter } from "next/font/google"
import "./globals.css"
import { AppQueryProvider } from "@/shared/lib/query"
import { ThemeProvider } from "@/shared/lib/theme"
import { HeaderRouter } from "@/widgets/header"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Joe Brundage | Software Engineer",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme') || 'system';
                  var resolvedTheme = theme;
                  var isToolsRoute = window.location.pathname === '/tools' || window.location.pathname.startsWith('/tools/');
                  if (!isToolsRoute && theme === 'terminal') {
                    theme = 'light';
                    resolvedTheme = 'light';
                    localStorage.setItem('theme', 'light');
                  }
                  if (isToolsRoute) {
                    resolvedTheme = 'terminal';
                  }
                  if (theme === 'system') {
                    resolvedTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                  }
                  if (isToolsRoute) {
                    resolvedTheme = 'terminal';
                  }
                  document.documentElement.classList.remove('terminal');
                  if (resolvedTheme === 'terminal') {
                    document.documentElement.classList.add('dark');
                    document.documentElement.classList.add('terminal');
                  } else if (resolvedTheme === 'dark') {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppQueryProvider>
          <ThemeProvider>
            <HeaderRouter />
            {children}
          </ThemeProvider>
        </AppQueryProvider>
      </body>
    </html>
  )
}
